// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Use environment variables for better security
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ||
  "https://bzyvoqvtijfgutrlteev.supabase.co";
const SUPABASE_ANON_KEY =
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6eXZvcXZ0aWpmZ3V0cmx0ZWV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NjIxOTMsImV4cCI6MjA2MzEzODE5M30.Oz5R8jmU88O6iDgb-GWoPDTeFwEGfe9SqnWuRysYQXc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);
